/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiCollectRouteImport } from './routes/api/collect'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRouteImport } from './routes/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectRoute = ApiCollectRouteImport.update({
  id: '/api/collect',
  path: '/api/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute =
  ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRouteImport.update({
    id: '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b',
    path: '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b': typeof ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b': typeof ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b': typeof ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/api/admin'
    | '/api/collect'
    | '/api/delete-account'
    | '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/api/admin'
    | '/api/collect'
    | '/api/delete-account'
    | '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
  id:
    | '__root__'
    | '/$'
    | '/api/admin'
    | '/api/collect'
    | '/api/delete-account'
    | '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiCollectRoute: typeof ApiCollectRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute: typeof ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collect': {
      id: '/api/collect'
      path: '/api/collect'
      fullPath: '/api/collect'
      preLoaderRoute: typeof ApiCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b': {
      id: '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
      path: '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
      fullPath: '/api/public/hooks/heartbeat-7f3a9b2e8c1d4a6b'
      preLoaderRoute: typeof ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiCollectRoute: ApiCollectRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute:
    ApiPublicHooksHeartbeat7f3a9b2e8c1d4a6bRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
